spring:
  profiles:
    active: test

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5441/postgres
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: none
    hibernate.format_sql: true #쿼리줄바꿈

  flyway:
    baseline-on-migrate: true
logging:
  level:
    root: DEBUG
    org.thymeleaf: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # 매개변수 바인딩 로그 출력
