# application-test.yml
spring:
  h2:
    console:
      enabled: true
      path: /db-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop  # 테스트 후 자동으로 테이블 삭제
logging:
  level:
    root: INFO
