spring:



  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5441/postgres
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: none